package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1485</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_AddNodesResult extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public IntValuedEnum<UA_StatusCode > statusCode() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public UA_AddNodesResult statusCode(IntValuedEnum<UA_StatusCode > statusCode) {
		this.io.setEnumField(this, 0, statusCode);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_NodeId addedNodeId() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_AddNodesResult addedNodeId(UA_NodeId addedNodeId) {
		this.io.setNativeObjectField(this, 1, addedNodeId);
		return this;
	}
	public UA_AddNodesResult() {
		super();
	}
	public UA_AddNodesResult(Pointer pointer) {
		super(pointer);
	}
}
