package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_NodeClass;
/**
 * <i>native declaration : open62541.h:1508</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_AddReferencesItem extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId sourceNodeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_AddReferencesItem sourceNodeId(UA_NodeId sourceNodeId) {
		this.io.setNativeObjectField(this, 0, sourceNodeId);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_NodeId referenceTypeId() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_AddReferencesItem referenceTypeId(UA_NodeId referenceTypeId) {
		this.io.setNativeObjectField(this, 1, referenceTypeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(2) 
	public boolean isForward() {
		return this.io.getBooleanField(this, 2);
	}
	/** C type : UA_Boolean */
	@Field(2) 
	public UA_AddReferencesItem isForward(boolean isForward) {
		this.io.setBooleanField(this, 2, isForward);
		return this;
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_String targetServerUri() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_AddReferencesItem targetServerUri(UA_String targetServerUri) {
		this.io.setNativeObjectField(this, 3, targetServerUri);
		return this;
	}
	/** C type : UA_ExpandedNodeId */
	@Field(4) 
	public UA_ExpandedNodeId targetNodeId() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(4) 
	public UA_AddReferencesItem targetNodeId(UA_ExpandedNodeId targetNodeId) {
		this.io.setNativeObjectField(this, 4, targetNodeId);
		return this;
	}
	/** C type : UA_NodeClass */
	@Field(5) 
	public IntValuedEnum<UA_NodeClass > targetNodeClass() {
		return this.io.getEnumField(this, 5);
	}
	/** C type : UA_NodeClass */
	@Field(5) 
	public UA_AddReferencesItem targetNodeClass(IntValuedEnum<UA_NodeClass > targetNodeClass) {
		this.io.setEnumField(this, 5, targetNodeClass);
		return this;
	}
	public UA_AddReferencesItem() {
		super();
	}
	public UA_AddReferencesItem(Pointer pointer) {
		super(pointer);
	}
}
