package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1855</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_BuildInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String productUri() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_BuildInfo productUri(UA_String productUri) {
		this.io.setNativeObjectField(this, 0, productUri);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String manufacturerName() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_BuildInfo manufacturerName(UA_String manufacturerName) {
		this.io.setNativeObjectField(this, 1, manufacturerName);
		return this;
	}
	/** C type : UA_String */
	@Field(2) 
	public UA_String productName() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_String */
	@Field(2) 
	public UA_BuildInfo productName(UA_String productName) {
		this.io.setNativeObjectField(this, 2, productName);
		return this;
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_String softwareVersion() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_BuildInfo softwareVersion(UA_String softwareVersion) {
		this.io.setNativeObjectField(this, 3, softwareVersion);
		return this;
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_String buildNumber() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_BuildInfo buildNumber(UA_String buildNumber) {
		this.io.setNativeObjectField(this, 4, buildNumber);
		return this;
	}
	/** C type : UA_DateTime */
	@Field(5) 
	public long buildDate() {
		return this.io.getLongField(this, 5);
	}
	/** C type : UA_DateTime */
	@Field(5) 
	public UA_BuildInfo buildDate(long buildDate) {
		this.io.setLongField(this, 5, buildDate);
		return this;
	}
	public UA_BuildInfo() {
		super();
	}
	public UA_BuildInfo(Pointer pointer) {
		super(pointer);
	}
}
