package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1622</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_BrowseRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_BrowseRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_ViewDescription */
	@Field(1) 
	public UA_ViewDescription view() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_ViewDescription */
	@Field(1) 
	public UA_BrowseRequest view(UA_ViewDescription view) {
		this.io.setNativeObjectField(this, 1, view);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public int requestedMaxReferencesPerNode() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public UA_BrowseRequest requestedMaxReferencesPerNode(int requestedMaxReferencesPerNode) {
		this.io.setIntField(this, 2, requestedMaxReferencesPerNode);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public int nodesToBrowseSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public UA_BrowseRequest nodesToBrowseSize(int nodesToBrowseSize) {
		this.io.setIntField(this, 3, nodesToBrowseSize);
		return this;
	}
	/** C type : UA_BrowseDescription* */
	@Field(4) 
	public Pointer<UA_BrowseDescription > nodesToBrowse() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : UA_BrowseDescription* */
	@Field(4) 
	public UA_BrowseRequest nodesToBrowse(Pointer<UA_BrowseDescription > nodesToBrowse) {
		this.io.setPointerField(this, 4, nodesToBrowse);
		return this;
	}
	public UA_BrowseRequest() {
		super();
	}
	public UA_BrowseRequest(Pointer pointer) {
		super(pointer);
	}
}
