package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_BrowseDirection;
/**
 * <i>native declaration : open62541.h:1584</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_BrowseDescription extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId nodeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_BrowseDescription nodeId(UA_NodeId nodeId) {
		this.io.setNativeObjectField(this, 0, nodeId);
		return this;
	}
	/** C type : UA_BrowseDirection */
	@Field(1) 
	public IntValuedEnum<UA_BrowseDirection > browseDirection() {
		return this.io.getEnumField(this, 1);
	}
	/** C type : UA_BrowseDirection */
	@Field(1) 
	public UA_BrowseDescription browseDirection(IntValuedEnum<UA_BrowseDirection > browseDirection) {
		this.io.setEnumField(this, 1, browseDirection);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(2) 
	public UA_NodeId referenceTypeId() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_NodeId */
	@Field(2) 
	public UA_BrowseDescription referenceTypeId(UA_NodeId referenceTypeId) {
		this.io.setNativeObjectField(this, 2, referenceTypeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(3) 
	public boolean includeSubtypes() {
		return this.io.getBooleanField(this, 3);
	}
	/** C type : UA_Boolean */
	@Field(3) 
	public UA_BrowseDescription includeSubtypes(boolean includeSubtypes) {
		this.io.setBooleanField(this, 3, includeSubtypes);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public int nodeClassMask() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public UA_BrowseDescription nodeClassMask(int nodeClassMask) {
		this.io.setIntField(this, 4, nodeClassMask);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(5) 
	public int resultMask() {
		return this.io.getIntField(this, 5);
	}
	/** C type : UA_UInt32 */
	@Field(5) 
	public UA_BrowseDescription resultMask(int resultMask) {
		this.io.setIntField(this, 5, resultMask);
		return this;
	}
	public UA_BrowseDescription() {
		super();
	}
	public UA_BrowseDescription(Pointer pointer) {
		super(pointer);
	}
}
