package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1673</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_BrowsePathResult extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public IntValuedEnum<UA_StatusCode > statusCode() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public UA_BrowsePathResult statusCode(IntValuedEnum<UA_StatusCode > statusCode) {
		this.io.setEnumField(this, 0, statusCode);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(1) 
	public int targetsSize() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_Int32 */
	@Field(1) 
	public UA_BrowsePathResult targetsSize(int targetsSize) {
		this.io.setIntField(this, 1, targetsSize);
		return this;
	}
	/** C type : UA_BrowsePathTarget* */
	@Field(2) 
	public Pointer<UA_BrowsePathTarget > targets() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : UA_BrowsePathTarget* */
	@Field(2) 
	public UA_BrowsePathResult targets(Pointer<UA_BrowsePathTarget > targets) {
		this.io.setPointerField(this, 2, targets);
		return this;
	}
	public UA_BrowsePathResult() {
		super();
	}
	public UA_BrowsePathResult(Pointer pointer) {
		super(pointer);
	}
}
