package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1807</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_CreateSubscriptionResponse extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_ResponseHeader responseHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_CreateSubscriptionResponse responseHeader(UA_ResponseHeader responseHeader) {
		this.io.setNativeObjectField(this, 0, responseHeader);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int subscriptionId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_CreateSubscriptionResponse subscriptionId(int subscriptionId) {
		this.io.setIntField(this, 1, subscriptionId);
		return this;
	}
	/** C type : UA_Double */
	@Field(2) 
	public double revisedPublishingInterval() {
		return this.io.getDoubleField(this, 2);
	}
	/** C type : UA_Double */
	@Field(2) 
	public UA_CreateSubscriptionResponse revisedPublishingInterval(double revisedPublishingInterval) {
		this.io.setDoubleField(this, 2, revisedPublishingInterval);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int revisedLifetimeCount() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_CreateSubscriptionResponse revisedLifetimeCount(int revisedLifetimeCount) {
		this.io.setIntField(this, 3, revisedLifetimeCount);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public int revisedMaxKeepAliveCount() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public UA_CreateSubscriptionResponse revisedMaxKeepAliveCount(int revisedMaxKeepAliveCount) {
		this.io.setIntField(this, 4, revisedMaxKeepAliveCount);
		return this;
	}
	public UA_CreateSubscriptionResponse() {
		super();
	}
	public UA_CreateSubscriptionResponse(Pointer pointer) {
		super(pointer);
	}
}
