package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_TimestampsToReturn;
/**
 * <i>native declaration : open62541.h:1784</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_CreateMonitoredItemsRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_CreateMonitoredItemsRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int subscriptionId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_CreateMonitoredItemsRequest subscriptionId(int subscriptionId) {
		this.io.setIntField(this, 1, subscriptionId);
		return this;
	}
	/** C type : UA_TimestampsToReturn */
	@Field(2) 
	public IntValuedEnum<UA_TimestampsToReturn > timestampsToReturn() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : UA_TimestampsToReturn */
	@Field(2) 
	public UA_CreateMonitoredItemsRequest timestampsToReturn(IntValuedEnum<UA_TimestampsToReturn > timestampsToReturn) {
		this.io.setEnumField(this, 2, timestampsToReturn);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public int itemsToCreateSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public UA_CreateMonitoredItemsRequest itemsToCreateSize(int itemsToCreateSize) {
		this.io.setIntField(this, 3, itemsToCreateSize);
		return this;
	}
	/** C type : UA_MonitoredItemCreateRequest* */
	@Field(4) 
	public Pointer<UA_MonitoredItemCreateRequest > itemsToCreate() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : UA_MonitoredItemCreateRequest* */
	@Field(4) 
	public UA_CreateMonitoredItemsRequest itemsToCreate(Pointer<UA_MonitoredItemCreateRequest > itemsToCreate) {
		this.io.setPointerField(this, 4, itemsToCreate);
		return this;
	}
	public UA_CreateMonitoredItemsRequest() {
		super();
	}
	public UA_CreateMonitoredItemsRequest(Pointer pointer) {
		super(pointer);
	}
}
