package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1800</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_CreateSubscriptionRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_CreateSubscriptionRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_Double */
	@Field(1) 
	public double requestedPublishingInterval() {
		return this.io.getDoubleField(this, 1);
	}
	/** C type : UA_Double */
	@Field(1) 
	public UA_CreateSubscriptionRequest requestedPublishingInterval(double requestedPublishingInterval) {
		this.io.setDoubleField(this, 1, requestedPublishingInterval);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public int requestedLifetimeCount() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public UA_CreateSubscriptionRequest requestedLifetimeCount(int requestedLifetimeCount) {
		this.io.setIntField(this, 2, requestedLifetimeCount);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int requestedMaxKeepAliveCount() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_CreateSubscriptionRequest requestedMaxKeepAliveCount(int requestedMaxKeepAliveCount) {
		this.io.setIntField(this, 3, requestedMaxKeepAliveCount);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public int maxNotificationsPerPublish() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public UA_CreateSubscriptionRequest maxNotificationsPerPublish(int maxNotificationsPerPublish) {
		this.io.setIntField(this, 4, maxNotificationsPerPublish);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(5) 
	public boolean publishingEnabled() {
		return this.io.getBooleanField(this, 5);
	}
	/** C type : UA_Boolean */
	@Field(5) 
	public UA_CreateSubscriptionRequest publishingEnabled(boolean publishingEnabled) {
		this.io.setBooleanField(this, 5, publishingEnabled);
		return this;
	}
	/** C type : UA_Byte */
	@Field(6) 
	public byte priority() {
		return this.io.getByteField(this, 6);
	}
	/** C type : UA_Byte */
	@Field(6) 
	public UA_CreateSubscriptionRequest priority(byte priority) {
		this.io.setByteField(this, 6, priority);
		return this;
	}
	public UA_CreateSubscriptionRequest() {
		super();
	}
	public UA_CreateSubscriptionRequest(Pointer pointer) {
		super(pointer);
	}
}
