package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1563</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_DeleteReferencesResponse extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_ResponseHeader responseHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_DeleteReferencesResponse responseHeader(UA_ResponseHeader responseHeader) {
		this.io.setNativeObjectField(this, 0, responseHeader);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(1) 
	public int resultsSize() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_Int32 */
	@Field(1) 
	public UA_DeleteReferencesResponse resultsSize(int resultsSize) {
		this.io.setIntField(this, 1, resultsSize);
		return this;
	}
	/** C type : UA_StatusCode* */
	@Field(2) 
	public Pointer<IntValuedEnum<UA_StatusCode > > results() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : UA_StatusCode* */
	@Field(2) 
	public UA_DeleteReferencesResponse results(Pointer<IntValuedEnum<UA_StatusCode > > results) {
		this.io.setPointerField(this, 2, results);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public int diagnosticInfosSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_Int32 */
	@Field(3) 
	public UA_DeleteReferencesResponse diagnosticInfosSize(int diagnosticInfosSize) {
		this.io.setIntField(this, 3, diagnosticInfosSize);
		return this;
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(4) 
	public Pointer<UA_DiagnosticInfo > diagnosticInfos() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(4) 
	public UA_DeleteReferencesResponse diagnosticInfos(Pointer<UA_DiagnosticInfo > diagnosticInfos) {
		this.io.setPointerField(this, 4, diagnosticInfos);
		return this;
	}
	public UA_DeleteReferencesResponse() {
		super();
	}
	public UA_DeleteReferencesResponse(Pointer pointer) {
		super(pointer);
	}
}
