package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:519</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_LocalizedText extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String locale() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_LocalizedText locale(UA_String locale) {
		this.io.setNativeObjectField(this, 0, locale);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String text() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_LocalizedText text(UA_String text) {
		this.io.setNativeObjectField(this, 1, text);
		return this;
	}
	public UA_LocalizedText() {
		super();
	}
	public UA_LocalizedText(Pointer pointer) {
		super(pointer);
	}
}
