package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1765</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_MonitoringParameters extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public int clientHandle() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public UA_MonitoringParameters clientHandle(int clientHandle) {
		this.io.setIntField(this, 0, clientHandle);
		return this;
	}
	/** C type : UA_Double */
	@Field(1) 
	public double samplingInterval() {
		return this.io.getDoubleField(this, 1);
	}
	/** C type : UA_Double */
	@Field(1) 
	public UA_MonitoringParameters samplingInterval(double samplingInterval) {
		this.io.setDoubleField(this, 1, samplingInterval);
		return this;
	}
	/** C type : UA_ExtensionObject */
	@Field(2) 
	public UA_ExtensionObject filter() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ExtensionObject */
	@Field(2) 
	public UA_MonitoringParameters filter(UA_ExtensionObject filter) {
		this.io.setNativeObjectField(this, 2, filter);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int queueSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_MonitoringParameters queueSize(int queueSize) {
		this.io.setIntField(this, 3, queueSize);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public boolean discardOldest() {
		return this.io.getBooleanField(this, 4);
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public UA_MonitoringParameters discardOldest(boolean discardOldest) {
		this.io.setBooleanField(this, 4, discardOldest);
		return this;
	}
	public UA_MonitoringParameters() {
		super();
	}
	public UA_MonitoringParameters(Pointer pointer) {
		super(pointer);
	}
}
