package org.point85.open62541;
import java.util.Collections;
import java.util.Iterator;
import org.bridj.BridJ;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : open62541.h:498</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_NodeId extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt16 */
	@Field(0) 
	public short namespaceIndex() {
		return this.io.getShortField(this, 0);
	}
	/** C type : UA_UInt16 */
	@Field(0) 
	public UA_NodeId namespaceIndex(short namespaceIndex) {
		this.io.setShortField(this, 0, namespaceIndex);
		return this;
	}
	/** C type : identifierType_enum */
	@Field(1) 
	public IntValuedEnum<UA_NodeId.identifierType_enum > identifierType() {
		return this.io.getEnumField(this, 1);
	}
	/** C type : identifierType_enum */
	@Field(1) 
	public UA_NodeId identifierType(IntValuedEnum<UA_NodeId.identifierType_enum > identifierType) {
		this.io.setEnumField(this, 1, identifierType);
		return this;
	}
	/** C type : identifier_union */
	@Field(2) 
	public UA_NodeId.identifier_union identifier() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : identifier_union */
	@Field(2) 
	public UA_NodeId identifier(UA_NodeId.identifier_union identifier) {
		this.io.setNativeObjectField(this, 2, identifier);
		return this;
	}
	/**
	 * enum values<br>
	 * <i>native declaration : open62541.h:491</i>
	 */
	public enum identifierType_enum implements IntValuedEnum<identifierType_enum > {
		UA_NODEIDTYPE_NUMERIC(2),
		UA_NODEIDTYPE_STRING(3),
		UA_NODEIDTYPE_GUID(4),
		UA_NODEIDTYPE_BYTESTRING(5);
		identifierType_enum(long value) {
			this.value = value;
		}
		public final long value;
		public long value() {
			return this.value;
		}
		public Iterator<identifierType_enum > iterator() {
			return Collections.singleton(this).iterator();
		}
		public static IntValuedEnum<identifierType_enum > fromValue(int value) {
			return FlagSet.fromValue(value, values());
		}
	};
	/** <i>native declaration : open62541.h:497</i> */
	@Union 
	public static class identifier_union extends StructObject {
		static {
			BridJ.register();
		}
		/** C type : UA_UInt32 */
		@Field(0) 
		public int numeric() {
			return this.io.getIntField(this, 0);
		}
		/** C type : UA_UInt32 */
		@Field(0) 
		public identifier_union numeric(int numeric) {
			this.io.setIntField(this, 0, numeric);
			return this;
		}
		/** C type : UA_String */
		@Field(1) 
		public UA_String string() {
			return this.io.getNativeObjectField(this, 1);
		}
		/** C type : UA_String */
		@Field(1) 
		public identifier_union string(UA_String string) {
			this.io.setNativeObjectField(this, 1, string);
			return this;
		}
		/** C type : UA_Guid */
		@Field(2) 
		public UA_Guid guid() {
			return this.io.getNativeObjectField(this, 2);
		}
		/** C type : UA_Guid */
		@Field(2) 
		public identifier_union guid(UA_Guid guid) {
			this.io.setNativeObjectField(this, 2, guid);
			return this;
		}
		/** C type : UA_ByteString */
		@Field(3) 
		public UA_String byteString() {
			return this.io.getNativeObjectField(this, 3);
		}
		/** C type : UA_ByteString */
		@Field(3) 
		public identifier_union byteString(UA_String byteString) {
			this.io.setNativeObjectField(this, 3, byteString);
			return this;
		}
		public identifier_union() {
			super();
		}
		public identifier_union(Pointer pointer) {
			super(pointer);
		}
	};
	public UA_NodeId() {
		super();
	}
	public UA_NodeId(Pointer pointer) {
		super(pointer);
	}
}
