package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:550</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_NumericRange extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_Int32 */
	@Field(0) 
	public int dimensionsSize() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_Int32 */
	@Field(0) 
	public UA_NumericRange dimensionsSize(int dimensionsSize) {
		this.io.setIntField(this, 0, dimensionsSize);
		return this;
	}
	/** C type : UA_NumericRangeDimension* */
	@Field(1) 
	public Pointer<UA_NumericRange.UA_NumericRangeDimension > dimensions() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : UA_NumericRangeDimension* */
	@Field(1) 
	public UA_NumericRange dimensions(Pointer<UA_NumericRange.UA_NumericRangeDimension > dimensions) {
		this.io.setPointerField(this, 1, dimensions);
		return this;
	}
	/** <i>native declaration : open62541.h:549</i> */
	public static class UA_NumericRangeDimension extends StructObject {
		static {
			BridJ.register();
		}
		/** C type : UA_UInt32 */
		@Field(0) 
		public int min() {
			return this.io.getIntField(this, 0);
		}
		/** C type : UA_UInt32 */
		@Field(0) 
		public UA_NumericRangeDimension min(int min) {
			this.io.setIntField(this, 0, min);
			return this;
		}
		/** C type : UA_UInt32 */
		@Field(1) 
		public int max() {
			return this.io.getIntField(this, 1);
		}
		/** C type : UA_UInt32 */
		@Field(1) 
		public UA_NumericRangeDimension max(int max) {
			this.io.setIntField(this, 1, max);
			return this;
		}
		public UA_NumericRangeDimension() {
			super();
		}
		public UA_NumericRangeDimension(Pointer pointer) {
			super(pointer);
		}
	};
	public UA_NumericRange() {
		super();
	}
	public UA_NumericRange(Pointer pointer) {
		super(pointer);
	}
}
