package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1847</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_PublishResponse extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_ResponseHeader responseHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_PublishResponse responseHeader(UA_ResponseHeader responseHeader) {
		this.io.setNativeObjectField(this, 0, responseHeader);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int subscriptionId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_PublishResponse subscriptionId(int subscriptionId) {
		this.io.setIntField(this, 1, subscriptionId);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public int availableSequenceNumbersSize() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public UA_PublishResponse availableSequenceNumbersSize(int availableSequenceNumbersSize) {
		this.io.setIntField(this, 2, availableSequenceNumbersSize);
		return this;
	}
	/** C type : UA_UInt32* */
	@Field(3) 
	public Pointer<Integer > availableSequenceNumbers() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : UA_UInt32* */
	@Field(3) 
	public UA_PublishResponse availableSequenceNumbers(Pointer<Integer > availableSequenceNumbers) {
		this.io.setPointerField(this, 3, availableSequenceNumbers);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public boolean moreNotifications() {
		return this.io.getBooleanField(this, 4);
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public UA_PublishResponse moreNotifications(boolean moreNotifications) {
		this.io.setBooleanField(this, 4, moreNotifications);
		return this;
	}
	/** C type : UA_NotificationMessage */
	@Field(5) 
	public UA_NotificationMessage notificationMessage() {
		return this.io.getNativeObjectField(this, 5);
	}
	/** C type : UA_NotificationMessage */
	@Field(5) 
	public UA_PublishResponse notificationMessage(UA_NotificationMessage notificationMessage) {
		this.io.setNativeObjectField(this, 5, notificationMessage);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public int resultsSize() {
		return this.io.getIntField(this, 6);
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public UA_PublishResponse resultsSize(int resultsSize) {
		this.io.setIntField(this, 6, resultsSize);
		return this;
	}
	/** C type : UA_StatusCode* */
	@Field(7) 
	public Pointer<IntValuedEnum<UA_StatusCode > > results() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : UA_StatusCode* */
	@Field(7) 
	public UA_PublishResponse results(Pointer<IntValuedEnum<UA_StatusCode > > results) {
		this.io.setPointerField(this, 7, results);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public int diagnosticInfosSize() {
		return this.io.getIntField(this, 8);
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public UA_PublishResponse diagnosticInfosSize(int diagnosticInfosSize) {
		this.io.setIntField(this, 8, diagnosticInfosSize);
		return this;
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(9) 
	public Pointer<UA_DiagnosticInfo > diagnosticInfos() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(9) 
	public UA_PublishResponse diagnosticInfos(Pointer<UA_DiagnosticInfo > diagnosticInfos) {
		this.io.setPointerField(this, 9, diagnosticInfos);
		return this;
	}
	public UA_PublishResponse() {
		super();
	}
	public UA_PublishResponse(Pointer pointer) {
		super(pointer);
	}
}
