package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1186</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ResponseHeader extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_DateTime */
	@Field(0) 
	public long timestamp() {
		return this.io.getLongField(this, 0);
	}
	/** C type : UA_DateTime */
	@Field(0) 
	public UA_ResponseHeader timestamp(long timestamp) {
		this.io.setLongField(this, 0, timestamp);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int requestHandle() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_ResponseHeader requestHandle(int requestHandle) {
		this.io.setIntField(this, 1, requestHandle);
		return this;
	}
	/** C type : UA_StatusCode */
	@Field(2) 
	public IntValuedEnum<UA_StatusCode > serviceResult() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : UA_StatusCode */
	@Field(2) 
	public UA_ResponseHeader serviceResult(IntValuedEnum<UA_StatusCode > serviceResult) {
		this.io.setEnumField(this, 2, serviceResult);
		return this;
	}
	/** C type : UA_DiagnosticInfo */
	@Field(3) 
	public UA_DiagnosticInfo serviceDiagnostics() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_DiagnosticInfo */
	@Field(3) 
	public UA_ResponseHeader serviceDiagnostics(UA_DiagnosticInfo serviceDiagnostics) {
		this.io.setNativeObjectField(this, 3, serviceDiagnostics);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public int stringTableSize() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public UA_ResponseHeader stringTableSize(int stringTableSize) {
		this.io.setIntField(this, 4, stringTableSize);
		return this;
	}
	/** C type : UA_String* */
	@Field(5) 
	public Pointer<UA_String > stringTable() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : UA_String* */
	@Field(5) 
	public UA_ResponseHeader stringTable(Pointer<UA_String > stringTable) {
		this.io.setPointerField(this, 5, stringTable);
		return this;
	}
	/** C type : UA_ExtensionObject */
	@Field(6) 
	public UA_ExtensionObject additionalHeader() {
		return this.io.getNativeObjectField(this, 6);
	}
	/** C type : UA_ExtensionObject */
	@Field(6) 
	public UA_ResponseHeader additionalHeader(UA_ExtensionObject additionalHeader) {
		this.io.setNativeObjectField(this, 6, additionalHeader);
		return this;
	}
	public UA_ResponseHeader() {
		super();
	}
	public UA_ResponseHeader(Pointer pointer) {
		super(pointer);
	}
}
