package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_NodeClass;
/**
 * <i>native declaration : open62541.h:1607</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ReferenceDescription extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId referenceTypeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_ReferenceDescription referenceTypeId(UA_NodeId referenceTypeId) {
		this.io.setNativeObjectField(this, 0, referenceTypeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public boolean isForward() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public UA_ReferenceDescription isForward(boolean isForward) {
		this.io.setBooleanField(this, 1, isForward);
		return this;
	}
	/** C type : UA_ExpandedNodeId */
	@Field(2) 
	public UA_ExpandedNodeId nodeId() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(2) 
	public UA_ReferenceDescription nodeId(UA_ExpandedNodeId nodeId) {
		this.io.setNativeObjectField(this, 2, nodeId);
		return this;
	}
	/** C type : UA_QualifiedName */
	@Field(3) 
	public UA_QualifiedName browseName() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_QualifiedName */
	@Field(3) 
	public UA_ReferenceDescription browseName(UA_QualifiedName browseName) {
		this.io.setNativeObjectField(this, 3, browseName);
		return this;
	}
	/** C type : UA_LocalizedText */
	@Field(4) 
	public UA_LocalizedText displayName() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_LocalizedText */
	@Field(4) 
	public UA_ReferenceDescription displayName(UA_LocalizedText displayName) {
		this.io.setNativeObjectField(this, 4, displayName);
		return this;
	}
	/** C type : UA_NodeClass */
	@Field(5) 
	public IntValuedEnum<UA_NodeClass > nodeClass() {
		return this.io.getEnumField(this, 5);
	}
	/** C type : UA_NodeClass */
	@Field(5) 
	public UA_ReferenceDescription nodeClass(IntValuedEnum<UA_NodeClass > nodeClass) {
		this.io.setEnumField(this, 5, nodeClass);
		return this;
	}
	/** C type : UA_ExpandedNodeId */
	@Field(6) 
	public UA_ExpandedNodeId typeDefinition() {
		return this.io.getNativeObjectField(this, 6);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(6) 
	public UA_ReferenceDescription typeDefinition(UA_ExpandedNodeId typeDefinition) {
		this.io.setNativeObjectField(this, 6, typeDefinition);
		return this;
	}
	public UA_ReferenceDescription() {
		super();
	}
	public UA_ReferenceDescription(Pointer pointer) {
		super(pointer);
	}
}
