package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1813</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_SetPublishingModeRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_SetPublishingModeRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public boolean publishingEnabled() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public UA_SetPublishingModeRequest publishingEnabled(boolean publishingEnabled) {
		this.io.setBooleanField(this, 1, publishingEnabled);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public int subscriptionIdsSize() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public UA_SetPublishingModeRequest subscriptionIdsSize(int subscriptionIdsSize) {
		this.io.setIntField(this, 2, subscriptionIdsSize);
		return this;
	}
	/** C type : UA_UInt32* */
	@Field(3) 
	public Pointer<Integer > subscriptionIds() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : UA_UInt32* */
	@Field(3) 
	public UA_SetPublishingModeRequest subscriptionIds(Pointer<Integer > subscriptionIds) {
		this.io.setPointerField(this, 3, subscriptionIds);
		return this;
	}
	public UA_SetPublishingModeRequest() {
		super();
	}
	public UA_SetPublishingModeRequest(Pointer pointer) {
		super(pointer);
	}
}
