package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1300</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_SignatureData extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String algorithm() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_SignatureData algorithm(UA_String algorithm) {
		this.io.setNativeObjectField(this, 0, algorithm);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(1) 
	public UA_String signature() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_ByteString */
	@Field(1) 
	public UA_SignatureData signature(UA_String signature) {
		this.io.setNativeObjectField(this, 1, signature);
		return this;
	}
	public UA_SignatureData() {
		super();
	}
	public UA_SignatureData(Pointer pointer) {
		super(pointer);
	}
}
