package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1982</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ServerConfig extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_Boolean */
	@Field(0) 
	public boolean Login_enableAnonymous() {
		return this.io.getBooleanField(this, 0);
	}
	/** C type : UA_Boolean */
	@Field(0) 
	public UA_ServerConfig Login_enableAnonymous(boolean Login_enableAnonymous) {
		this.io.setBooleanField(this, 0, Login_enableAnonymous);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public boolean Login_enableUsernamePassword() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public UA_ServerConfig Login_enableUsernamePassword(boolean Login_enableUsernamePassword) {
		this.io.setBooleanField(this, 1, Login_enableUsernamePassword);
		return this;
	}
	/** C type : char** */
	@Field(2) 
	public Pointer<Pointer<Byte > > Login_usernames() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : char** */
	@Field(2) 
	public UA_ServerConfig Login_usernames(Pointer<Pointer<Byte > > Login_usernames) {
		this.io.setPointerField(this, 2, Login_usernames);
		return this;
	}
	/** C type : char** */
	@Field(3) 
	public Pointer<Pointer<Byte > > Login_passwords() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : char** */
	@Field(3) 
	public UA_ServerConfig Login_passwords(Pointer<Pointer<Byte > > Login_passwords) {
		this.io.setPointerField(this, 3, Login_passwords);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public int Login_loginsCount() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public UA_ServerConfig Login_loginsCount(int Login_loginsCount) {
		this.io.setIntField(this, 4, Login_loginsCount);
		return this;
	}
	/** C type : char* */
	@Field(5) 
	public Pointer<Byte > Application_applicationURI() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : char* */
	@Field(5) 
	public UA_ServerConfig Application_applicationURI(Pointer<Byte > Application_applicationURI) {
		this.io.setPointerField(this, 5, Application_applicationURI);
		return this;
	}
	/** C type : char* */
	@Field(6) 
	public Pointer<Byte > Application_applicationName() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : char* */
	@Field(6) 
	public UA_ServerConfig Application_applicationName(Pointer<Byte > Application_applicationName) {
		this.io.setPointerField(this, 6, Application_applicationName);
		return this;
	}
	public UA_ServerConfig() {
		super();
	}
	public UA_ServerConfig(Pointer pointer) {
		super(pointer);
	}
}
