package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1830</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_SubscriptionAcknowledgement extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public int subscriptionId() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public UA_SubscriptionAcknowledgement subscriptionId(int subscriptionId) {
		this.io.setIntField(this, 0, subscriptionId);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int sequenceNumber() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_SubscriptionAcknowledgement sequenceNumber(int sequenceNumber) {
		this.io.setIntField(this, 1, sequenceNumber);
		return this;
	}
	public UA_SubscriptionAcknowledgement() {
		super();
	}
	public UA_SubscriptionAcknowledgement(Pointer pointer) {
		super(pointer);
	}
}
