package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1342</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_UserNameIdentityToken extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String policyId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_UserNameIdentityToken policyId(UA_String policyId) {
		this.io.setNativeObjectField(this, 0, policyId);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String userName() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_UserNameIdentityToken userName(UA_String userName) {
		this.io.setNativeObjectField(this, 1, userName);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(2) 
	public UA_String password() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ByteString */
	@Field(2) 
	public UA_UserNameIdentityToken password(UA_String password) {
		this.io.setNativeObjectField(this, 2, password);
		return this;
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_String encryptionAlgorithm() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_String */
	@Field(3) 
	public UA_UserNameIdentityToken encryptionAlgorithm(UA_String encryptionAlgorithm) {
		this.io.setNativeObjectField(this, 3, encryptionAlgorithm);
		return this;
	}
	public UA_UserNameIdentityToken() {
		super();
	}
	public UA_UserNameIdentityToken(Pointer pointer) {
		super(pointer);
	}
}
