package org.point85.open62541;
import java.util.Collections;
import java.util.Iterator;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.ann.Union;
/**
 * <i>native declaration : open62541.h:2087</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_WorkItem extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : type_enum */
	@Field(0) 
	public IntValuedEnum<UA_WorkItem.type_enum > type() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : type_enum */
	@Field(0) 
	public UA_WorkItem type(IntValuedEnum<UA_WorkItem.type_enum > type) {
		this.io.setEnumField(this, 0, type);
		return this;
	}
	/** C type : work_union */
	@Field(1) 
	public UA_WorkItem.work_union work() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : work_union */
	@Field(1) 
	public UA_WorkItem work(UA_WorkItem.work_union work) {
		this.io.setNativeObjectField(this, 1, work);
		return this;
	}
	/**
	 * enum values<br>
	 * <i>native declaration : open62541.h:2072</i>
	 */
	public enum type_enum implements IntValuedEnum<type_enum > {
		UA_WORKITEMTYPE_NOTHING(0),
		UA_WORKITEMTYPE_CLOSECONNECTION(1),
		UA_WORKITEMTYPE_BINARYMESSAGE(2),
		UA_WORKITEMTYPE_METHODCALL(3),
		UA_WORKITEMTYPE_DELAYEDMETHODCALL(4);
		type_enum(long value) {
			this.value = value;
		}
		public final long value;
		public long value() {
			return this.value;
		}
		public Iterator<type_enum > iterator() {
			return Collections.singleton(this).iterator();
		}
		public static IntValuedEnum<type_enum > fromValue(int value) {
			return FlagSet.fromValue(value, values());
		}
	};
	/** <i>native declaration : open62541.h:2086</i> */
	@Union 
	public static class work_union extends StructObject {
		static {
			BridJ.register();
		}
		/** C type : UA_Connection* */
		@Field(0) 
		public Pointer<UA_Connection > closeConnection() {
			return this.io.getPointerField(this, 0);
		}
		/** C type : UA_Connection* */
		@Field(0) 
		public work_union closeConnection(Pointer<UA_Connection > closeConnection) {
			this.io.setPointerField(this, 0, closeConnection);
			return this;
		}
		/** C type : binaryMessage_struct */
		@Field(1) 
		public UA_WorkItem.work_union.binaryMessage_struct binaryMessage() {
			return this.io.getNativeObjectField(this, 1);
		}
		/** C type : binaryMessage_struct */
		@Field(1) 
		public work_union binaryMessage(UA_WorkItem.work_union.binaryMessage_struct binaryMessage) {
			this.io.setNativeObjectField(this, 1, binaryMessage);
			return this;
		}
		/** C type : methodCall_struct */
		@Field(2) 
		public UA_WorkItem.work_union.methodCall_struct methodCall() {
			return this.io.getNativeObjectField(this, 2);
		}
		/** C type : methodCall_struct */
		@Field(2) 
		public work_union methodCall(UA_WorkItem.work_union.methodCall_struct methodCall) {
			this.io.setNativeObjectField(this, 2, methodCall);
			return this;
		}
		/** <i>native declaration : open62541.h:2080</i> */
		public static class binaryMessage_struct extends StructObject {
			static {
				BridJ.register();
			}
			/** C type : UA_Connection* */
			@Field(0) 
			public Pointer<UA_Connection > connection() {
				return this.io.getPointerField(this, 0);
			}
			/** C type : UA_Connection* */
			@Field(0) 
			public binaryMessage_struct connection(Pointer<UA_Connection > connection) {
				this.io.setPointerField(this, 0, connection);
				return this;
			}
			/** C type : UA_ByteString */
			@Field(1) 
			public UA_String message() {
				return this.io.getNativeObjectField(this, 1);
			}
			/** C type : UA_ByteString */
			@Field(1) 
			public binaryMessage_struct message(UA_String message) {
				this.io.setNativeObjectField(this, 1, message);
				return this;
			}
			public binaryMessage_struct() {
				super();
			}
			public binaryMessage_struct(Pointer pointer) {
				super(pointer);
			}
		};
		/** <i>native declaration : open62541.h:2085</i> */
		public static class methodCall_struct extends StructObject {
			static {
				BridJ.register();
			}
			/** C type : void* */
			@Field(0) 
			public Pointer<? > data() {
				return this.io.getPointerField(this, 0);
			}
			/** C type : void* */
			@Field(0) 
			public methodCall_struct data(Pointer<? > data) {
				this.io.setPointerField(this, 0, data);
				return this;
			}
			/** C type : method_callback* */
			@Field(1) 
			public Pointer<UA_WorkItem.work_union.methodCall_struct.method_callback > method() {
				return this.io.getPointerField(this, 1);
			}
			/** C type : method_callback* */
			@Field(1) 
			public methodCall_struct method(Pointer<UA_WorkItem.work_union.methodCall_struct.method_callback > method) {
				this.io.setPointerField(this, 1, method);
				return this;
			}
			/** <i>native declaration : open62541.h:2084</i> */
			public static abstract class method_callback extends Callback<method_callback > {
				public void apply(Pointer<UA_Server > server, Pointer<? > data) {
					apply(Pointer.getPeer(server), Pointer.getPeer(data));
				}
				public void apply(@Ptr long server, @Ptr long data) {
					apply((Pointer)Pointer.pointerToAddress(server, UA_Server.class), Pointer.pointerToAddress(data));
				}
			};
			public methodCall_struct() {
				super();
			}
			public methodCall_struct(Pointer pointer) {
				super(pointer);
			}
		};
		public work_union() {
			super();
		}
		public work_union(Pointer pointer) {
			super(pointer);
		}
	};
	public UA_WorkItem() {
		super();
	}
	public UA_WorkItem(Pointer pointer) {
		super(pointer);
	}
}
