package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1353</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ActivateSessionRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_ActivateSessionRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_SignatureData */
	@Field(1) 
	public UA_SignatureData clientSignature() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_SignatureData */
	@Field(1) 
	public UA_ActivateSessionRequest clientSignature(UA_SignatureData clientSignature) {
		this.io.setNativeObjectField(this, 1, clientSignature);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public int clientSoftwareCertificatesSize() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public UA_ActivateSessionRequest clientSoftwareCertificatesSize(int clientSoftwareCertificatesSize) {
		this.io.setIntField(this, 2, clientSoftwareCertificatesSize);
		return this;
	}
	/** C type : UA_SignedSoftwareCertificate* */
	@Field(3) 
	public Pointer<UA_SignedSoftwareCertificate > clientSoftwareCertificates() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : UA_SignedSoftwareCertificate* */
	@Field(3) 
	public UA_ActivateSessionRequest clientSoftwareCertificates(Pointer<UA_SignedSoftwareCertificate > clientSoftwareCertificates) {
		this.io.setPointerField(this, 3, clientSoftwareCertificates);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public int localeIdsSize() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public UA_ActivateSessionRequest localeIdsSize(int localeIdsSize) {
		this.io.setIntField(this, 4, localeIdsSize);
		return this;
	}
	/** C type : UA_String* */
	@Field(5) 
	public Pointer<UA_String > localeIds() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : UA_String* */
	@Field(5) 
	public UA_ActivateSessionRequest localeIds(Pointer<UA_String > localeIds) {
		this.io.setPointerField(this, 5, localeIds);
		return this;
	}
	/** C type : UA_ExtensionObject */
	@Field(6) 
	public UA_ExtensionObject userIdentityToken() {
		return this.io.getNativeObjectField(this, 6);
	}
	/** C type : UA_ExtensionObject */
	@Field(6) 
	public UA_ActivateSessionRequest userIdentityToken(UA_ExtensionObject userIdentityToken) {
		this.io.setNativeObjectField(this, 6, userIdentityToken);
		return this;
	}
	/** C type : UA_SignatureData */
	@Field(7) 
	public UA_SignatureData userTokenSignature() {
		return this.io.getNativeObjectField(this, 7);
	}
	/** C type : UA_SignatureData */
	@Field(7) 
	public UA_ActivateSessionRequest userTokenSignature(UA_SignatureData userTokenSignature) {
		this.io.setNativeObjectField(this, 7, userTokenSignature);
		return this;
	}
	public UA_ActivateSessionRequest() {
		super();
	}
	public UA_ActivateSessionRequest(Pointer pointer) {
		super(pointer);
	}
}
