package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_ApplicationType;
/**
 * <i>native declaration : open62541.h:1166</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ApplicationDescription extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String applicationUri() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_ApplicationDescription applicationUri(UA_String applicationUri) {
		this.io.setNativeObjectField(this, 0, applicationUri);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String productUri() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_ApplicationDescription productUri(UA_String productUri) {
		this.io.setNativeObjectField(this, 1, productUri);
		return this;
	}
	/** C type : UA_LocalizedText */
	@Field(2) 
	public UA_LocalizedText applicationName() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_LocalizedText */
	@Field(2) 
	public UA_ApplicationDescription applicationName(UA_LocalizedText applicationName) {
		this.io.setNativeObjectField(this, 2, applicationName);
		return this;
	}
	/** C type : UA_ApplicationType */
	@Field(3) 
	public IntValuedEnum<UA_ApplicationType > applicationType() {
		return this.io.getEnumField(this, 3);
	}
	/** C type : UA_ApplicationType */
	@Field(3) 
	public UA_ApplicationDescription applicationType(IntValuedEnum<UA_ApplicationType > applicationType) {
		this.io.setEnumField(this, 3, applicationType);
		return this;
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_String gatewayServerUri() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_ApplicationDescription gatewayServerUri(UA_String gatewayServerUri) {
		this.io.setNativeObjectField(this, 4, gatewayServerUri);
		return this;
	}
	/** C type : UA_String */
	@Field(5) 
	public UA_String discoveryProfileUri() {
		return this.io.getNativeObjectField(this, 5);
	}
	/** C type : UA_String */
	@Field(5) 
	public UA_ApplicationDescription discoveryProfileUri(UA_String discoveryProfileUri) {
		this.io.setNativeObjectField(this, 5, discoveryProfileUri);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public int discoveryUrlsSize() {
		return this.io.getIntField(this, 6);
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public UA_ApplicationDescription discoveryUrlsSize(int discoveryUrlsSize) {
		this.io.setIntField(this, 6, discoveryUrlsSize);
		return this;
	}
	/** C type : UA_String* */
	@Field(7) 
	public Pointer<UA_String > discoveryUrls() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : UA_String* */
	@Field(7) 
	public UA_ApplicationDescription discoveryUrls(Pointer<UA_String > discoveryUrls) {
		this.io.setPointerField(this, 7, discoveryUrls);
		return this;
	}
	public UA_ApplicationDescription() {
		super();
	}
	public UA_ApplicationDescription(Pointer pointer) {
		super(pointer);
	}
}
