package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1667</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_BrowsePathTarget extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ExpandedNodeId */
	@Field(0) 
	public UA_ExpandedNodeId targetId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(0) 
	public UA_BrowsePathTarget targetId(UA_ExpandedNodeId targetId) {
		this.io.setNativeObjectField(this, 0, targetId);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int remainingPathIndex() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_BrowsePathTarget remainingPathIndex(int remainingPathIndex) {
		this.io.setIntField(this, 1, remainingPathIndex);
		return this;
	}
	public UA_BrowsePathTarget() {
		super();
	}
	public UA_BrowsePathTarget(Pointer pointer) {
		super(pointer);
	}
}
