package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1894</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ConnectionConfig extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public int protocolVersion() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public UA_ConnectionConfig protocolVersion(int protocolVersion) {
		this.io.setIntField(this, 0, protocolVersion);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int sendBufferSize() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_ConnectionConfig sendBufferSize(int sendBufferSize) {
		this.io.setIntField(this, 1, sendBufferSize);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public int recvBufferSize() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_UInt32 */
	@Field(2) 
	public UA_ConnectionConfig recvBufferSize(int recvBufferSize) {
		this.io.setIntField(this, 2, recvBufferSize);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int maxMessageSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_ConnectionConfig maxMessageSize(int maxMessageSize) {
		this.io.setIntField(this, 3, maxMessageSize);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public int maxChunkCount() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_UInt32 */
	@Field(4) 
	public UA_ConnectionConfig maxChunkCount(int maxChunkCount) {
		this.io.setIntField(this, 4, maxChunkCount);
		return this;
	}
	public UA_ConnectionConfig() {
		super();
	}
	public UA_ConnectionConfig(Pointer pointer) {
		super(pointer);
	}
}
