package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1266</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ChannelSecurityToken extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public int channelId() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_UInt32 */
	@Field(0) 
	public UA_ChannelSecurityToken channelId(int channelId) {
		this.io.setIntField(this, 0, channelId);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int tokenId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_ChannelSecurityToken tokenId(int tokenId) {
		this.io.setIntField(this, 1, tokenId);
		return this;
	}
	/** C type : UA_DateTime */
	@Field(2) 
	public long createdAt() {
		return this.io.getLongField(this, 2);
	}
	/** C type : UA_DateTime */
	@Field(2) 
	public UA_ChannelSecurityToken createdAt(long createdAt) {
		this.io.setLongField(this, 2, createdAt);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int revisedLifetime() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_ChannelSecurityToken revisedLifetime(int revisedLifetime) {
		this.io.setIntField(this, 3, revisedLifetime);
		return this;
	}
	public UA_ChannelSecurityToken() {
		super();
	}
	public UA_ChannelSecurityToken(Pointer pointer) {
		super(pointer);
	}
}
