package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1327</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_CreateSessionResponse extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_ResponseHeader responseHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_CreateSessionResponse responseHeader(UA_ResponseHeader responseHeader) {
		this.io.setNativeObjectField(this, 0, responseHeader);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_NodeId sessionId() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_CreateSessionResponse sessionId(UA_NodeId sessionId) {
		this.io.setNativeObjectField(this, 1, sessionId);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(2) 
	public UA_NodeId authenticationToken() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_NodeId */
	@Field(2) 
	public UA_CreateSessionResponse authenticationToken(UA_NodeId authenticationToken) {
		this.io.setNativeObjectField(this, 2, authenticationToken);
		return this;
	}
	/** C type : UA_Double */
	@Field(3) 
	public double revisedSessionTimeout() {
		return this.io.getDoubleField(this, 3);
	}
	/** C type : UA_Double */
	@Field(3) 
	public UA_CreateSessionResponse revisedSessionTimeout(double revisedSessionTimeout) {
		this.io.setDoubleField(this, 3, revisedSessionTimeout);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(4) 
	public UA_String serverNonce() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_ByteString */
	@Field(4) 
	public UA_CreateSessionResponse serverNonce(UA_String serverNonce) {
		this.io.setNativeObjectField(this, 4, serverNonce);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(5) 
	public UA_String serverCertificate() {
		return this.io.getNativeObjectField(this, 5);
	}
	/** C type : UA_ByteString */
	@Field(5) 
	public UA_CreateSessionResponse serverCertificate(UA_String serverCertificate) {
		this.io.setNativeObjectField(this, 5, serverCertificate);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public int serverEndpointsSize() {
		return this.io.getIntField(this, 6);
	}
	/** C type : UA_Int32 */
	@Field(6) 
	public UA_CreateSessionResponse serverEndpointsSize(int serverEndpointsSize) {
		this.io.setIntField(this, 6, serverEndpointsSize);
		return this;
	}
	/** C type : UA_EndpointDescription* */
	@Field(7) 
	public Pointer<UA_EndpointDescription > serverEndpoints() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : UA_EndpointDescription* */
	@Field(7) 
	public UA_CreateSessionResponse serverEndpoints(Pointer<UA_EndpointDescription > serverEndpoints) {
		this.io.setPointerField(this, 7, serverEndpoints);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public int serverSoftwareCertificatesSize() {
		return this.io.getIntField(this, 8);
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public UA_CreateSessionResponse serverSoftwareCertificatesSize(int serverSoftwareCertificatesSize) {
		this.io.setIntField(this, 8, serverSoftwareCertificatesSize);
		return this;
	}
	/** C type : UA_SignedSoftwareCertificate* */
	@Field(9) 
	public Pointer<UA_SignedSoftwareCertificate > serverSoftwareCertificates() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : UA_SignedSoftwareCertificate* */
	@Field(9) 
	public UA_CreateSessionResponse serverSoftwareCertificates(Pointer<UA_SignedSoftwareCertificate > serverSoftwareCertificates) {
		this.io.setPointerField(this, 9, serverSoftwareCertificates);
		return this;
	}
	/** C type : UA_SignatureData */
	@Field(10) 
	public UA_SignatureData serverSignature() {
		return this.io.getNativeObjectField(this, 10);
	}
	/** C type : UA_SignatureData */
	@Field(10) 
	public UA_CreateSessionResponse serverSignature(UA_SignatureData serverSignature) {
		this.io.setNativeObjectField(this, 10, serverSignature);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(11) 
	public int maxRequestMessageSize() {
		return this.io.getIntField(this, 11);
	}
	/** C type : UA_UInt32 */
	@Field(11) 
	public UA_CreateSessionResponse maxRequestMessageSize(int maxRequestMessageSize) {
		this.io.setIntField(this, 11, maxRequestMessageSize);
		return this;
	}
	public UA_CreateSessionResponse() {
		super();
	}
	public UA_CreateSessionResponse(Pointer pointer) {
		super(pointer);
	}
}
