package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1367</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_CloseSessionRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_CloseSessionRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public boolean deleteSubscriptions() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public UA_CloseSessionRequest deleteSubscriptions(boolean deleteSubscriptions) {
		this.io.setBooleanField(this, 1, deleteSubscriptions);
		return this;
	}
	public UA_CloseSessionRequest() {
		super();
	}
	public UA_CloseSessionRequest(Pointer pointer) {
		super(pointer);
	}
}
