package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1549</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_DeleteReferencesItem extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId sourceNodeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_DeleteReferencesItem sourceNodeId(UA_NodeId sourceNodeId) {
		this.io.setNativeObjectField(this, 0, sourceNodeId);
		return this;
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_NodeId referenceTypeId() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_NodeId */
	@Field(1) 
	public UA_DeleteReferencesItem referenceTypeId(UA_NodeId referenceTypeId) {
		this.io.setNativeObjectField(this, 1, referenceTypeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(2) 
	public boolean isForward() {
		return this.io.getBooleanField(this, 2);
	}
	/** C type : UA_Boolean */
	@Field(2) 
	public UA_DeleteReferencesItem isForward(boolean isForward) {
		this.io.setBooleanField(this, 2, isForward);
		return this;
	}
	/** C type : UA_ExpandedNodeId */
	@Field(3) 
	public UA_ExpandedNodeId targetNodeId() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(3) 
	public UA_DeleteReferencesItem targetNodeId(UA_ExpandedNodeId targetNodeId) {
		this.io.setNativeObjectField(this, 3, targetNodeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public boolean deleteBidirectional() {
		return this.io.getBooleanField(this, 4);
	}
	/** C type : UA_Boolean */
	@Field(4) 
	public UA_DeleteReferencesItem deleteBidirectional(boolean deleteBidirectional) {
		this.io.setBooleanField(this, 4, deleteBidirectional);
		return this;
	}
	public UA_DeleteReferencesItem() {
		super();
	}
	public UA_DeleteReferencesItem(Pointer pointer) {
		super(pointer);
	}
}
