package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Bits;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:612</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_DiagnosticInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_Boolean */
	@Field(0) 
	@Bits(1) 
	public boolean hasSymbolicId() {
		return this.io.getBooleanField(this, 0);
	}
	/** C type : UA_Boolean */
	@Field(0) 
	@Bits(1) 
	public UA_DiagnosticInfo hasSymbolicId(boolean hasSymbolicId) {
		this.io.setBooleanField(this, 0, hasSymbolicId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	@Bits(1) 
	public boolean hasNamespaceUri() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	@Bits(1) 
	public UA_DiagnosticInfo hasNamespaceUri(boolean hasNamespaceUri) {
		this.io.setBooleanField(this, 1, hasNamespaceUri);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(2) 
	@Bits(1) 
	public boolean hasLocalizedText() {
		return this.io.getBooleanField(this, 2);
	}
	/** C type : UA_Boolean */
	@Field(2) 
	@Bits(1) 
	public UA_DiagnosticInfo hasLocalizedText(boolean hasLocalizedText) {
		this.io.setBooleanField(this, 2, hasLocalizedText);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(3) 
	@Bits(1) 
	public boolean hasLocale() {
		return this.io.getBooleanField(this, 3);
	}
	/** C type : UA_Boolean */
	@Field(3) 
	@Bits(1) 
	public UA_DiagnosticInfo hasLocale(boolean hasLocale) {
		this.io.setBooleanField(this, 3, hasLocale);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(4) 
	@Bits(1) 
	public boolean hasAdditionalInfo() {
		return this.io.getBooleanField(this, 4);
	}
	/** C type : UA_Boolean */
	@Field(4) 
	@Bits(1) 
	public UA_DiagnosticInfo hasAdditionalInfo(boolean hasAdditionalInfo) {
		this.io.setBooleanField(this, 4, hasAdditionalInfo);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(5) 
	@Bits(1) 
	public boolean hasInnerStatusCode() {
		return this.io.getBooleanField(this, 5);
	}
	/** C type : UA_Boolean */
	@Field(5) 
	@Bits(1) 
	public UA_DiagnosticInfo hasInnerStatusCode(boolean hasInnerStatusCode) {
		this.io.setBooleanField(this, 5, hasInnerStatusCode);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(6) 
	@Bits(1) 
	public boolean hasInnerDiagnosticInfo() {
		return this.io.getBooleanField(this, 6);
	}
	/** C type : UA_Boolean */
	@Field(6) 
	@Bits(1) 
	public UA_DiagnosticInfo hasInnerDiagnosticInfo(boolean hasInnerDiagnosticInfo) {
		this.io.setBooleanField(this, 6, hasInnerDiagnosticInfo);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(7) 
	public int symbolicId() {
		return this.io.getIntField(this, 7);
	}
	/** C type : UA_Int32 */
	@Field(7) 
	public UA_DiagnosticInfo symbolicId(int symbolicId) {
		this.io.setIntField(this, 7, symbolicId);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public int namespaceUri() {
		return this.io.getIntField(this, 8);
	}
	/** C type : UA_Int32 */
	@Field(8) 
	public UA_DiagnosticInfo namespaceUri(int namespaceUri) {
		this.io.setIntField(this, 8, namespaceUri);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(9) 
	public int localizedText() {
		return this.io.getIntField(this, 9);
	}
	/** C type : UA_Int32 */
	@Field(9) 
	public UA_DiagnosticInfo localizedText(int localizedText) {
		this.io.setIntField(this, 9, localizedText);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(10) 
	public int locale() {
		return this.io.getIntField(this, 10);
	}
	/** C type : UA_Int32 */
	@Field(10) 
	public UA_DiagnosticInfo locale(int locale) {
		this.io.setIntField(this, 10, locale);
		return this;
	}
	/** C type : UA_String */
	@Field(11) 
	public UA_String additionalInfo() {
		return this.io.getNativeObjectField(this, 11);
	}
	/** C type : UA_String */
	@Field(11) 
	public UA_DiagnosticInfo additionalInfo(UA_String additionalInfo) {
		this.io.setNativeObjectField(this, 11, additionalInfo);
		return this;
	}
	/** C type : UA_StatusCode */
	@Field(12) 
	public IntValuedEnum<UA_StatusCode > innerStatusCode() {
		return this.io.getEnumField(this, 12);
	}
	/** C type : UA_StatusCode */
	@Field(12) 
	public UA_DiagnosticInfo innerStatusCode(IntValuedEnum<UA_StatusCode > innerStatusCode) {
		this.io.setEnumField(this, 12, innerStatusCode);
		return this;
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(13) 
	public Pointer<UA_DiagnosticInfo > innerDiagnosticInfo() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : UA_DiagnosticInfo* */
	@Field(13) 
	public UA_DiagnosticInfo innerDiagnosticInfo(Pointer<UA_DiagnosticInfo > innerDiagnosticInfo) {
		this.io.setPointerField(this, 13, innerDiagnosticInfo);
		return this;
	}
	public UA_DiagnosticInfo() {
		super();
	}
	public UA_DiagnosticInfo(Pointer pointer) {
		super(pointer);
	}
}
