package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:862</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_DateTimeStruct extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_Int16 */
	@Field(0) 
	public short nanoSec() {
		return this.io.getShortField(this, 0);
	}
	/** C type : UA_Int16 */
	@Field(0) 
	public UA_DateTimeStruct nanoSec(short nanoSec) {
		this.io.setShortField(this, 0, nanoSec);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(1) 
	public short microSec() {
		return this.io.getShortField(this, 1);
	}
	/** C type : UA_Int16 */
	@Field(1) 
	public UA_DateTimeStruct microSec(short microSec) {
		this.io.setShortField(this, 1, microSec);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(2) 
	public short milliSec() {
		return this.io.getShortField(this, 2);
	}
	/** C type : UA_Int16 */
	@Field(2) 
	public UA_DateTimeStruct milliSec(short milliSec) {
		this.io.setShortField(this, 2, milliSec);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(3) 
	public short sec() {
		return this.io.getShortField(this, 3);
	}
	/** C type : UA_Int16 */
	@Field(3) 
	public UA_DateTimeStruct sec(short sec) {
		this.io.setShortField(this, 3, sec);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(4) 
	public short min() {
		return this.io.getShortField(this, 4);
	}
	/** C type : UA_Int16 */
	@Field(4) 
	public UA_DateTimeStruct min(short min) {
		this.io.setShortField(this, 4, min);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(5) 
	public short hour() {
		return this.io.getShortField(this, 5);
	}
	/** C type : UA_Int16 */
	@Field(5) 
	public UA_DateTimeStruct hour(short hour) {
		this.io.setShortField(this, 5, hour);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(6) 
	public short day() {
		return this.io.getShortField(this, 6);
	}
	/** C type : UA_Int16 */
	@Field(6) 
	public UA_DateTimeStruct day(short day) {
		this.io.setShortField(this, 6, day);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(7) 
	public short month() {
		return this.io.getShortField(this, 7);
	}
	/** C type : UA_Int16 */
	@Field(7) 
	public UA_DateTimeStruct month(short month) {
		this.io.setShortField(this, 7, month);
		return this;
	}
	/** C type : UA_Int16 */
	@Field(8) 
	public short year() {
		return this.io.getShortField(this, 8);
	}
	/** C type : UA_Int16 */
	@Field(8) 
	public UA_DateTimeStruct year(short year) {
		this.io.setShortField(this, 8, year);
		return this;
	}
	public UA_DateTimeStruct() {
		super();
	}
	public UA_DateTimeStruct(Pointer pointer) {
		super(pointer);
	}
}
