package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_MessageSecurityMode;
/**
 * <i>native declaration : open62541.h:1239</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_EndpointDescription extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_String endpointUrl() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_String */
	@Field(0) 
	public UA_EndpointDescription endpointUrl(UA_String endpointUrl) {
		this.io.setNativeObjectField(this, 0, endpointUrl);
		return this;
	}
	/** C type : UA_ApplicationDescription */
	@Field(1) 
	public UA_ApplicationDescription server() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_ApplicationDescription */
	@Field(1) 
	public UA_EndpointDescription server(UA_ApplicationDescription server) {
		this.io.setNativeObjectField(this, 1, server);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(2) 
	public UA_String serverCertificate() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ByteString */
	@Field(2) 
	public UA_EndpointDescription serverCertificate(UA_String serverCertificate) {
		this.io.setNativeObjectField(this, 2, serverCertificate);
		return this;
	}
	/** C type : UA_MessageSecurityMode */
	@Field(3) 
	public IntValuedEnum<UA_MessageSecurityMode > securityMode() {
		return this.io.getEnumField(this, 3);
	}
	/** C type : UA_MessageSecurityMode */
	@Field(3) 
	public UA_EndpointDescription securityMode(IntValuedEnum<UA_MessageSecurityMode > securityMode) {
		this.io.setEnumField(this, 3, securityMode);
		return this;
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_String securityPolicyUri() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_String */
	@Field(4) 
	public UA_EndpointDescription securityPolicyUri(UA_String securityPolicyUri) {
		this.io.setNativeObjectField(this, 4, securityPolicyUri);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(5) 
	public int userIdentityTokensSize() {
		return this.io.getIntField(this, 5);
	}
	/** C type : UA_Int32 */
	@Field(5) 
	public UA_EndpointDescription userIdentityTokensSize(int userIdentityTokensSize) {
		this.io.setIntField(this, 5, userIdentityTokensSize);
		return this;
	}
	/** C type : UA_UserTokenPolicy* */
	@Field(6) 
	public Pointer<UA_UserTokenPolicy > userIdentityTokens() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : UA_UserTokenPolicy* */
	@Field(6) 
	public UA_EndpointDescription userIdentityTokens(Pointer<UA_UserTokenPolicy > userIdentityTokens) {
		this.io.setPointerField(this, 6, userIdentityTokens);
		return this;
	}
	/** C type : UA_String */
	@Field(7) 
	public UA_String transportProfileUri() {
		return this.io.getNativeObjectField(this, 7);
	}
	/** C type : UA_String */
	@Field(7) 
	public UA_EndpointDescription transportProfileUri(UA_String transportProfileUri) {
		this.io.setNativeObjectField(this, 7, transportProfileUri);
		return this;
	}
	/** C type : UA_Byte */
	@Field(8) 
	public byte securityLevel() {
		return this.io.getByteField(this, 8);
	}
	/** C type : UA_Byte */
	@Field(8) 
	public UA_EndpointDescription securityLevel(byte securityLevel) {
		this.io.setByteField(this, 8, securityLevel);
		return this;
	}
	public UA_EndpointDescription() {
		super();
	}
	public UA_EndpointDescription(Pointer pointer) {
		super(pointer);
	}
}
