package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1199</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_FindServersRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_FindServersRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String endpointUrl() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_FindServersRequest endpointUrl(UA_String endpointUrl) {
		this.io.setNativeObjectField(this, 1, endpointUrl);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public int localeIdsSize() {
		return this.io.getIntField(this, 2);
	}
	/** C type : UA_Int32 */
	@Field(2) 
	public UA_FindServersRequest localeIdsSize(int localeIdsSize) {
		this.io.setIntField(this, 2, localeIdsSize);
		return this;
	}
	/** C type : UA_String* */
	@Field(3) 
	public Pointer<UA_String > localeIds() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : UA_String* */
	@Field(3) 
	public UA_FindServersRequest localeIds(Pointer<UA_String > localeIds) {
		this.io.setPointerField(this, 3, localeIds);
		return this;
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public int serverUrisSize() {
		return this.io.getIntField(this, 4);
	}
	/** C type : UA_Int32 */
	@Field(4) 
	public UA_FindServersRequest serverUrisSize(int serverUrisSize) {
		this.io.setIntField(this, 4, serverUrisSize);
		return this;
	}
	/** C type : UA_String* */
	@Field(5) 
	public Pointer<UA_String > serverUris() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : UA_String* */
	@Field(5) 
	public UA_FindServersRequest serverUris(Pointer<UA_String > serverUris) {
		this.io.setPointerField(this, 5, serverUris);
		return this;
	}
	public UA_FindServersRequest() {
		super();
	}
	public UA_FindServersRequest(Pointer pointer) {
		super(pointer);
	}
}
