package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_MonitoringMode;
/**
 * <i>native declaration : open62541.h:1770</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_MonitoredItemCreateRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ReadValueId */
	@Field(0) 
	public UA_ReadValueId itemToMonitor() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ReadValueId */
	@Field(0) 
	public UA_MonitoredItemCreateRequest itemToMonitor(UA_ReadValueId itemToMonitor) {
		this.io.setNativeObjectField(this, 0, itemToMonitor);
		return this;
	}
	/** C type : UA_MonitoringMode */
	@Field(1) 
	public IntValuedEnum<UA_MonitoringMode > monitoringMode() {
		return this.io.getEnumField(this, 1);
	}
	/** C type : UA_MonitoringMode */
	@Field(1) 
	public UA_MonitoredItemCreateRequest monitoringMode(IntValuedEnum<UA_MonitoringMode > monitoringMode) {
		this.io.setEnumField(this, 1, monitoringMode);
		return this;
	}
	/** C type : UA_MonitoringParameters */
	@Field(2) 
	public UA_MonitoringParameters requestedParameters() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_MonitoringParameters */
	@Field(2) 
	public UA_MonitoredItemCreateRequest requestedParameters(UA_MonitoringParameters requestedParameters) {
		this.io.setNativeObjectField(this, 2, requestedParameters);
		return this;
	}
	public UA_MonitoredItemCreateRequest() {
		super();
	}
	public UA_MonitoredItemCreateRequest(Pointer pointer) {
		super(pointer);
	}
}
