package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_StatusCode;
/**
 * <i>native declaration : open62541.h:1777</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_MonitoredItemCreateResult extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public IntValuedEnum<UA_StatusCode > statusCode() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : UA_StatusCode */
	@Field(0) 
	public UA_MonitoredItemCreateResult statusCode(IntValuedEnum<UA_StatusCode > statusCode) {
		this.io.setEnumField(this, 0, statusCode);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int monitoredItemId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_MonitoredItemCreateResult monitoredItemId(int monitoredItemId) {
		this.io.setIntField(this, 1, monitoredItemId);
		return this;
	}
	/** C type : UA_Double */
	@Field(2) 
	public double revisedSamplingInterval() {
		return this.io.getDoubleField(this, 2);
	}
	/** C type : UA_Double */
	@Field(2) 
	public UA_MonitoredItemCreateResult revisedSamplingInterval(double revisedSamplingInterval) {
		this.io.setDoubleField(this, 2, revisedSamplingInterval);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public int revisedQueueSize() {
		return this.io.getIntField(this, 3);
	}
	/** C type : UA_UInt32 */
	@Field(3) 
	public UA_MonitoredItemCreateResult revisedQueueSize(int revisedQueueSize) {
		this.io.setIntField(this, 3, revisedQueueSize);
		return this;
	}
	/** C type : UA_ExtensionObject */
	@Field(4) 
	public UA_ExtensionObject filterResult() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_ExtensionObject */
	@Field(4) 
	public UA_MonitoredItemCreateResult filterResult(UA_ExtensionObject filterResult) {
		this.io.setNativeObjectField(this, 4, filterResult);
		return this;
	}
	public UA_MonitoredItemCreateResult() {
		super();
	}
	public UA_MonitoredItemCreateResult(Pointer pointer) {
		super(pointer);
	}
}
