package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.point85.open62541.Open62541ExtLibrary.UA_MessageSecurityMode;
import org.point85.open62541.Open62541ExtLibrary.UA_SecurityTokenRequestType;
/**
 * <i>native declaration : open62541.h:1275</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_OpenSecureChannelRequest extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_RequestHeader requestHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_RequestHeader */
	@Field(0) 
	public UA_OpenSecureChannelRequest requestHeader(UA_RequestHeader requestHeader) {
		this.io.setNativeObjectField(this, 0, requestHeader);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int clientProtocolVersion() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_OpenSecureChannelRequest clientProtocolVersion(int clientProtocolVersion) {
		this.io.setIntField(this, 1, clientProtocolVersion);
		return this;
	}
	/** C type : UA_SecurityTokenRequestType */
	@Field(2) 
	public IntValuedEnum<UA_SecurityTokenRequestType > requestType() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : UA_SecurityTokenRequestType */
	@Field(2) 
	public UA_OpenSecureChannelRequest requestType(IntValuedEnum<UA_SecurityTokenRequestType > requestType) {
		this.io.setEnumField(this, 2, requestType);
		return this;
	}
	/** C type : UA_MessageSecurityMode */
	@Field(3) 
	public IntValuedEnum<UA_MessageSecurityMode > securityMode() {
		return this.io.getEnumField(this, 3);
	}
	/** C type : UA_MessageSecurityMode */
	@Field(3) 
	public UA_OpenSecureChannelRequest securityMode(IntValuedEnum<UA_MessageSecurityMode > securityMode) {
		this.io.setEnumField(this, 3, securityMode);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(4) 
	public UA_String clientNonce() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : UA_ByteString */
	@Field(4) 
	public UA_OpenSecureChannelRequest clientNonce(UA_String clientNonce) {
		this.io.setNativeObjectField(this, 4, clientNonce);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(5) 
	public int requestedLifetime() {
		return this.io.getIntField(this, 5);
	}
	/** C type : UA_UInt32 */
	@Field(5) 
	public UA_OpenSecureChannelRequest requestedLifetime(int requestedLifetime) {
		this.io.setIntField(this, 5, requestedLifetime);
		return this;
	}
	public UA_OpenSecureChannelRequest() {
		super();
	}
	public UA_OpenSecureChannelRequest(Pointer pointer) {
		super(pointer);
	}
}
