package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1282</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_OpenSecureChannelResponse extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_ResponseHeader responseHeader() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_ResponseHeader */
	@Field(0) 
	public UA_OpenSecureChannelResponse responseHeader(UA_ResponseHeader responseHeader) {
		this.io.setNativeObjectField(this, 0, responseHeader);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int serverProtocolVersion() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_OpenSecureChannelResponse serverProtocolVersion(int serverProtocolVersion) {
		this.io.setIntField(this, 1, serverProtocolVersion);
		return this;
	}
	/** C type : UA_ChannelSecurityToken */
	@Field(2) 
	public UA_ChannelSecurityToken securityToken() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ChannelSecurityToken */
	@Field(2) 
	public UA_OpenSecureChannelResponse securityToken(UA_ChannelSecurityToken securityToken) {
		this.io.setNativeObjectField(this, 2, securityToken);
		return this;
	}
	/** C type : UA_ByteString */
	@Field(3) 
	public UA_String serverNonce() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_ByteString */
	@Field(3) 
	public UA_OpenSecureChannelResponse serverNonce(UA_String serverNonce) {
		this.io.setNativeObjectField(this, 3, serverNonce);
		return this;
	}
	public UA_OpenSecureChannelResponse() {
		super();
	}
	public UA_OpenSecureChannelResponse(Pointer pointer) {
		super(pointer);
	}
}
