package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:514</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_QualifiedName extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_UInt16 */
	@Field(0) 
	public short namespaceIndex() {
		return this.io.getShortField(this, 0);
	}
	/** C type : UA_UInt16 */
	@Field(0) 
	public UA_QualifiedName namespaceIndex(short namespaceIndex) {
		this.io.setShortField(this, 0, namespaceIndex);
		return this;
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_String name() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : UA_String */
	@Field(1) 
	public UA_QualifiedName name(UA_String name) {
		this.io.setNativeObjectField(this, 1, name);
		return this;
	}
	public UA_QualifiedName() {
		super();
	}
	public UA_QualifiedName(Pointer pointer) {
		super(pointer);
	}
}
