package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1657</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_RelativePath extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_Int32 */
	@Field(0) 
	public int elementsSize() {
		return this.io.getIntField(this, 0);
	}
	/** C type : UA_Int32 */
	@Field(0) 
	public UA_RelativePath elementsSize(int elementsSize) {
		this.io.setIntField(this, 0, elementsSize);
		return this;
	}
	/** C type : UA_RelativePathElement* */
	@Field(1) 
	public Pointer<UA_RelativePathElement > elements() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : UA_RelativePathElement* */
	@Field(1) 
	public UA_RelativePath elements(Pointer<UA_RelativePathElement > elements) {
		this.io.setPointerField(this, 1, elements);
		return this;
	}
	public UA_RelativePath() {
		super();
	}
	public UA_RelativePath(Pointer pointer) {
		super(pointer);
	}
}
