package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1148</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_ReferenceNode extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId referenceTypeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_ReferenceNode referenceTypeId(UA_NodeId referenceTypeId) {
		this.io.setNativeObjectField(this, 0, referenceTypeId);
		return this;
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public boolean isInverse() {
		return this.io.getBooleanField(this, 1);
	}
	/** C type : UA_Boolean */
	@Field(1) 
	public UA_ReferenceNode isInverse(boolean isInverse) {
		this.io.setBooleanField(this, 1, isInverse);
		return this;
	}
	/** C type : UA_ExpandedNodeId */
	@Field(2) 
	public UA_ExpandedNodeId targetId() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_ExpandedNodeId */
	@Field(2) 
	public UA_ReferenceNode targetId(UA_ExpandedNodeId targetId) {
		this.io.setNativeObjectField(this, 2, targetId);
		return this;
	}
	public UA_ReferenceNode() {
		super();
	}
	public UA_ReferenceNode(Pointer pointer) {
		super(pointer);
	}
}
