package org.point85.open62541;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : open62541.h:1741</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Open62541Ext") 
public class UA_WriteValue extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_NodeId nodeId() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : UA_NodeId */
	@Field(0) 
	public UA_WriteValue nodeId(UA_NodeId nodeId) {
		this.io.setNativeObjectField(this, 0, nodeId);
		return this;
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public int attributeId() {
		return this.io.getIntField(this, 1);
	}
	/** C type : UA_UInt32 */
	@Field(1) 
	public UA_WriteValue attributeId(int attributeId) {
		this.io.setIntField(this, 1, attributeId);
		return this;
	}
	/** C type : UA_String */
	@Field(2) 
	public UA_String indexRange() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : UA_String */
	@Field(2) 
	public UA_WriteValue indexRange(UA_String indexRange) {
		this.io.setNativeObjectField(this, 2, indexRange);
		return this;
	}
	/** C type : UA_DataValue */
	@Field(3) 
	public UA_DataValue value() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : UA_DataValue */
	@Field(3) 
	public UA_WriteValue value(UA_DataValue value) {
		this.io.setNativeObjectField(this, 3, value);
		return this;
	}
	public UA_WriteValue() {
		super();
	}
	public UA_WriteValue(Pointer pointer) {
		super(pointer);
	}
}
